unit TestUsuarioSingleton;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, FireDAC.Comp.Client, UsuarioSingleton, UsuarioDados, SysUtils;

type
  // Test methods for class TUsuarioSingleton

  ExcecaoEsperada = class(Exception);
  TestTUsuarioSingleton = class(TTestCase)
  strict private
    FUsuarioSingleton: TUsuarioSingleton;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFazerLogin;
    procedure TestCriarUsuario;
  end;

implementation

procedure TestTUsuarioSingleton.SetUp;
begin
  ExpectedException := ExcecaoEsperada;
  DMUsuarioDados := TDMUsuarioDados.Create(nil);
  TUsuarioSingleton.GetInstance.SetQuery(DMUsuarioDados.FdqUsuario);
end;

procedure TestTUsuarioSingleton.TearDown;
begin
  DMUsuarioDados.Free;
  DMUsuarioDados := nil;
end;

procedure TestTUsuarioSingleton.TestCriarUsuario;
var
  ReturnValue: Boolean;
begin
  //Senhas diferentes
  ReturnValue := TUsuarioSingleton.GetInstance.CriarUsuario('icaro@gmail.com', 'icaro', '123', '456');
  CheckFalse(ReturnValue);

  //Sucesso
  ReturnValue := TUsuarioSingleton.GetInstance.CriarUsuario('icaro@gmail.com', 'icaro', '123', '123');
  CheckTrue(ReturnValue);

  //Usuário já cadastrado
  ReturnValue := TUsuarioSingleton.GetInstance.CriarUsuario('icaro@gmail.com', 'icaro', '123', '123');
  CheckFalse(ReturnValue);
end;

procedure TestTUsuarioSingleton.TestFazerLogin;
var
  ReturnValue: Boolean;
begin
  //Sucesso
  ReturnValue := TUsuarioSingleton.GetInstance.FazerLogin('icaro@gmail.com', '123');
  CheckTrue(ReturnValue);

  //Senha incorreta
  ReturnValue := TUsuarioSingleton.GetInstance.FazerLogin('icaro@gmail.com', '456');
  CheckFalse(ReturnValue);

  //Usuário não existe
  ReturnValue := TUsuarioSingleton.GetInstance.FazerLogin('UsuarioQueNaoExiste@gmail.com', '123');
  CheckFalse(ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTUsuarioSingleton.Suite);
end.

